#!/usr/bin/env python3
"""
corpus_stats_table.py — Compute Spjallrómur corpus statistics and emit a LaTeX table.

Usage:
    python stats/corpus_stats_table.py \
        --corpus-root /path/to/clarin/spjallromur \
        --transcript-root /path/to/spjallromur-v2 \
        --output-root /path/to/pipeline/output

All values are computed from the data files; no manual constants need editing.
The manual transcription coverage stats are read from
  <corpus-root>/.../docs/manual_transcripts_anon.json
(generated by anonymise_manual_transcripts.py).  The non-anonymised original
is used as a fallback if the anon file is not present.
"""

import argparse
import json
from pathlib import Path
from collections import Counter, defaultdict


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def clarin_session_dirs(corpus_root: Path, conv_type: str) -> list[Path]:
    """Return sorted list of session directories for a CLARIN conversation type."""
    base = corpus_root / "spjallromur" / "data" / conv_type
    if not base.exists():
        hits = [p for p in corpus_root.rglob(conv_type) if p.is_dir()]
        base = hits[0] if hits else None
    if base is None or not base.exists():
        return []
    return sorted(p for p in base.iterdir() if p.is_dir())


def clarin_speaker_count(corpus_root: Path, conv_type: str) -> int:
    return sum(
        1 for _ in corpus_root.rglob("speaker_*_convo_*_demographics.json")
        if conv_type in _.parts
    )


def v2_session_dirs(transcript_root: Path, conv_type: str) -> list[Path]:
    base = transcript_root / conv_type
    if not base.exists():
        return []
    return sorted(p for p in base.iterdir() if p.is_dir())


def find_v2_stem(transcript_root: Path, session_id: str, speaker: str) -> str | None:
    for p in transcript_root.rglob(f"{speaker}_{session_id}_*.json"):
        parts = p.stem.split("_")
        if len(parts) >= 4 and parts[0] == speaker and parts[1] == session_id:
            return p.stem
    return None


def age_gender_from_stem(stem: str) -> tuple[str, str]:
    parts = stem.split("_")
    age    = parts[2] if len(parts) >= 3 else ""
    gender = parts[3] if len(parts) >= 4 else ""
    return age, gender


def fmt_num(value, *, precision: int = 1, unit: str = "") -> str:
    if value is None:
        return r"\NUM{?}"
    s = f"{value:.{precision}f}"
    return f"{s}{unit}" if unit else s


def pct(n: int, total: int) -> str:
    return f"{round(n / total * 100)}\\%"


# ---------------------------------------------------------------------------
# Manual transcript coverage
# ---------------------------------------------------------------------------

def find_manual_transcripts_file(corpus_root: Path) -> Path | None:
    """Prefer the anonymised version; fall back to the original."""
    anon = next(corpus_root.rglob("manual_transcripts_anon.json"), None)
    if anon is not None:
        return anon
    original = next(corpus_root.rglob("manual_transcripts.json"), None)
    if original is not None:
        print(f"  NOTE: using non-anonymised manual_transcripts.json (run anonymise_manual_transcripts.py to produce the _anon version)")
    return original


def compute_manual_transcript_stats(corpus_root: Path) -> dict:
    """
    Returns:
      manually_transcribed_sessions  — unique sessions with ≥1 manual transcript
      triple_annotator_sessions      — sessions with Tiro + 2 manual transcribers
      dual_annotator_sessions        — sessions with Tiro + 1 manual transcriber
      total_manual_h                 — summed duration of the unique sessions (hours)
    """
    path = find_manual_transcripts_file(corpus_root)
    if path is None:
        return {
            "manually_transcribed_sessions": None,
            "triple_annotator_sessions":     None,
            "dual_annotator_sessions":       None,
            "total_manual_h":                None,
            "manual_transcripts_found":      False,
        }

    data = json.loads(path.read_text(encoding="utf-8"))
    convs = data.get("conversations", [])

    # Count manual transcribers per session
    session_transcribers: dict[str, set] = defaultdict(set)
    session_duration: dict[str, float] = {}
    for c in convs:
        sid = c["session_id"]
        session_transcribers[sid].add(c["transcriber"])
        dur = max(
            c.get("speaker_a", {}).get("recordingDuration", 0),
            c.get("speaker_b", {}).get("recordingDuration", 0),
        )
        session_duration[sid] = dur  # same for all entries of the same session

    unique_sessions    = len(session_transcribers)
    triple_sessions    = sum(1 for ts in session_transcribers.values() if len(ts) == 2)
    dual_sessions      = sum(1 for ts in session_transcribers.values() if len(ts) == 1)
    total_manual_h     = sum(session_duration.values()) / 3600

    return {
        "manually_transcribed_sessions": unique_sessions,
        "triple_annotator_sessions":     triple_sessions,
        "dual_annotator_sessions":       dual_sessions,
        "total_manual_h":                total_manual_h,
        "manual_transcripts_found":      True,
    }


# ---------------------------------------------------------------------------
# Main computation
# ---------------------------------------------------------------------------

def compute_stats(corpus_root: Path, transcript_root: Path, output_root: Path) -> dict:
    stats = {}

    # --- Full corpus (CLARIN) ---
    clarin_full_dirs = clarin_session_dirs(corpus_root, "full_conversations")
    clarin_half_dirs = clarin_session_dirs(corpus_root, "half_conversations")
    stats["clarin_full_sessions"]  = len(clarin_full_dirs)
    stats["clarin_half_sessions"]  = len(clarin_half_dirs)
    stats["clarin_total_sessions"] = len(clarin_full_dirs) + len(clarin_half_dirs)
    stats["clarin_total_spk"]      = (
        clarin_speaker_count(corpus_root, "full_conversations")
        + clarin_speaker_count(corpus_root, "half_conversations")
    )

    # Excluded sessions
    excluded_ids = set()
    for params_path in output_root.rglob("session_params.json"):
        params = json.loads(params_path.read_text())
        if params.get("status") == "excluded":
            excluded_ids.add(params["session_id"])
    stats["excluded_sessions"] = len(excluded_ids)

    # --- Processed (mixed) subset ---
    processed_sessions = []
    for params_path in sorted(output_root.rglob("session_params.json")):
        params = json.loads(params_path.read_text())
        if params.get("status") != "excluded" and "duration_a_sec" in params:
            processed_sessions.append(params)

    stats["processed_sessions"] = len(processed_sessions)

    durations = [max(p["duration_a_sec"], p["duration_b_sec"]) for p in processed_sessions]
    stats["total_duration_h"]  = sum(durations) / 3600
    stats["mean_duration_min"] = (sum(durations) / len(durations)) / 60 if durations else 0
    stats["min_duration_min"]  = min(durations) / 60 if durations else 0
    stats["max_duration_min"]  = max(durations) / 60 if durations else 0

    # --- Speaker demographics ---
    age_counter    = Counter()
    gender_counter = Counter()
    missing_stems  = []
    total_spk      = 0

    clarin_full_ids = {d.name for d in clarin_full_dirs}
    processed_ids   = {p["session_id"] for p in processed_sessions}

    for session_id in sorted(processed_ids & clarin_full_ids):
        for spk in ("a", "b"):
            total_spk += 1
            stem = find_v2_stem(transcript_root, session_id, spk)
            if stem:
                age, gender = age_gender_from_stem(stem)
                age_counter[age]       += 1
                gender_counter[gender] += 1
            else:
                missing_stems.append(f"{session_id}/{spk}")

    stats["total_spk_processed"] = total_spk
    stats["missing_stems"]       = missing_stems
    stats["gender"]              = dict(gender_counter)
    stats["age"]                 = dict(age_counter)

    def age_lower(age_str: str) -> int:
        return int(age_str.split("-")[0].rstrip("+"))

    stats["age_18_29"]  = sum(n for a, n in age_counter.items() if a and age_lower(a) < 30)
    stats["age_30_39"]  = sum(n for a, n in age_counter.items() if a and 30 <= age_lower(a) <= 39)
    stats["age_40_49"]  = sum(n for a, n in age_counter.items() if a and 40 <= age_lower(a) <= 49)
    stats["age_50plus"] = sum(n for a, n in age_counter.items() if a and age_lower(a) >= 50)

    # --- Manual transcription coverage ---
    stats.update(compute_manual_transcript_stats(corpus_root))

    return stats


# ---------------------------------------------------------------------------
# LaTeX table generation
# ---------------------------------------------------------------------------

def generate_table(s: dict) -> str:
    n_spk = s["total_spk_processed"]

    n_m = s["gender"].get("m", 0)
    n_f = s["gender"].get("f", 0)
    n_o = s["gender"].get("o", 0)

    n_18 = s["age_18_29"]
    n_30 = s["age_30_39"]
    n_40 = s["age_40_49"]
    n_50 = s["age_50plus"]

    total_h   = fmt_num(s["total_duration_h"],  precision=1, unit=" h")
    mean_min  = fmt_num(s["mean_duration_min"],  precision=1, unit=" min")
    range_min = (
        f"{fmt_num(s['min_duration_min'], precision=1)}"
        f"--{fmt_num(s['max_duration_min'], precision=1)} min"
    )

    mt_sess  = fmt_num(s["manually_transcribed_sessions"], precision=0)
    triple   = fmt_num(s["triple_annotator_sessions"],     precision=0)
    dual     = fmt_num(s["dual_annotator_sessions"],       precision=0)
    mt_hours = fmt_num(s["total_manual_h"],                precision=1, unit=" h")

    lines = [
        r"\begin{table}[t]",
        r"  \caption{Spjallr\'{o}mur corpus statistics.}",
        r"  \label{tab:corpus-stats}",
        r"  \centering",
        r"  \begin{tabular}{lr}",
        r"    \toprule",
        r"    Property & Value \\",
        r"    \midrule",
        r"    \multicolumn{2}{l}{\textit{Full corpus (CLARIN v2 release)}} \\",
        f"    Total recorded conversations      & {s['clarin_total_sessions']} \\\\",
        f"    \\quad Full conversations (both channels) & {s['clarin_full_sessions']} \\\\",
        f"    \\quad Half conversations (one channel)   & {s['clarin_half_sessions']} \\\\",
        f"    Total speaker recordings          & {s['clarin_total_spk']} \\\\",
        r"    \midrule",
        r"    \multicolumn{2}{l}{\textit{Dual-channel mixed subset (this work)}} \\",
        f"    Sessions processed                & {s['processed_sessions']} \\\\",
        f"    \\quad Excluded (bad audio)        & {s['excluded_sessions']} \\\\",
        f"    Total duration                    & {total_h} \\\\",
        f"    Session duration: mean            & {mean_min} \\\\",
        f"    Session duration: range           & {range_min} \\\\",
        r"    \multicolumn{2}{l}{\textit{\quad Speaker demographics (full conversations)}} \\",
        f"    \\quad Male                        & {n_m} ({pct(n_m, n_spk)}) \\\\",
        f"    \\quad Female                      & {n_f} ({pct(n_f, n_spk)}) \\\\",
        f"    \\quad Other                       & {n_o} ({pct(n_o, n_spk)}) \\\\",
        f"    Age 18--29                        & {n_18} ({pct(n_18, n_spk)}) \\\\",
        f"    Age 30--39                        & {n_30} ({pct(n_30, n_spk)}) \\\\",
        f"    Age 40--49                        & {n_40} ({pct(n_40, n_spk)}) \\\\",
        f"    Age 50+                           & {n_50} ({pct(n_50, n_spk)}) \\\\",
        r"    \midrule",
        r"    \multicolumn{2}{l}{\textit{Transcription coverage}} \\",
        f"    Tiro semi-automatic transcripts   & All {s['clarin_total_sessions']} sessions \\\\",
        f"    Manually transcribed sessions     & {mt_sess} \\\\",
        f"    \\quad Triple annotator coverage   & {triple} \\\\",
        f"    \\quad Dual annotator coverage     & {dual} \\\\",
        f"    Total manual transcription        & {mt_hours} \\\\",
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate LaTeX corpus statistics table.")
    parser.add_argument("--corpus-root",     required=True, help="CLARIN corpus root.")
    parser.add_argument("--transcript-root", required=True, help="v2 transcript root.")
    parser.add_argument("--output-root",     required=True, help="Pipeline output root.")
    args = parser.parse_args()

    corpus_root     = Path(args.corpus_root).expanduser().resolve()
    transcript_root = Path(args.transcript_root).expanduser().resolve()
    output_root     = Path(args.output_root).expanduser().resolve()

    s = compute_stats(corpus_root, transcript_root, output_root)

    print("=== Computed values ===")
    for k, v in s.items():
        if k not in ("gender", "age", "missing_stems"):
            print(f"  {k}: {v}")
    print(f"  gender: {s['gender']}")
    print(f"  age:    {s['age']}")
    if s["missing_stems"]:
        print(f"  WARNING — no v2 stem found for: {s['missing_stems']}")

    print("\n=== LaTeX table ===\n")
    print(generate_table(s))


if __name__ == "__main__":
    main()
